name: Continuous Integration

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Verify Docker Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: voult:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
